language: go
os: linux
arch: amd64
dist: trusty
sudo: required
git:
  strategy: clone
  depth: 1
  quiet: true

services:
- redis-server

before_install:
- nvm install node
- gimme stable
- sudo apt-get -y install libzmq3-dev
- sudo apt-get -y upgrade build-essential


install:
- go env CGO_ENABLED
- cd node-layer
- npm install
- cd ..
- openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out tlscert.crt -keyout tlskey.key

script:
- go test ./...
