language: go
go: "1.15"
os: linux
arch: amd64
dist: bionic
sudo: required
git:
  strategy: clone
  depth: 1
  quiet: true

services:
- redis-server

before_install:
- nvm install node
- sudo apt-get -y install libzmq3-dev


install:
- go env CGO_ENABLED
- cd node-layer
- npm install
- cd ..
- openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out tlscert.crt -keyout tlskey.key -subj "/C=US/ST=California/L=Los Angeles/O=Laplace Game Development/CN=www.example.com"

script:
- go test ./...
